TelePSocial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TelePSocial.Areas.Identity.Data;
using TelePSocial.Data;
using TelePSocial.Models;

namespace TelePSocial.Controllers
{  
    //[Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly TelePSociaDblContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        public HomeController(ILogger<HomeController> logger,UserManager<ApplicationUser> userManager, 
            SignInManager<ApplicationUser> signInManager, TelePSociaDblContext context)
        {
            _userManager = userManager;
            _context = context;
            _signInManager = signInManager;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account", new { area = "Identity" });
            }
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            ViewBag.nombre = user.Nombre_Usuario;
            ViewBag.photo = user.PhotoPerfil;
            ViewBag.DesImage = user.DesImage; 
            var List = await _context.PubliUsers.Where(z => !z.IdUser.Equals(user.UserName)).OrderByDescending(z => z.FecPublic).ToListAsync();
            foreach(var item in List)
            {
                item.CantiLikes = await _context.LikesPublics.Where(z => z.idPubliUsers.Equals(item.idPubliUsers)).CountAsync();
                var canlike = await _context.LikesPublics.Where(z => z.idPubliUsers.Equals(item.idPubliUsers) && z.IdUser.Equals(user.UserName)).CountAsync();
                item.Comentarios = await _context.CommentUsers.Where(z => z.idPubliUsers.Equals(item.idPubliUsers)).ToListAsync();
                item.userpubli = await _userManager.FindByNameAsync(item.IdUser);
                 
                foreach (var items in item.Comentarios)
                {
                    var usuarioComent = await _userManager.FindByNameAsync(items.IdUser);
                    items.username = usuarioComent.UserName;
                    items.usuario = usuarioComent.Nombre_Usuario;
                    items.desPhoto = usuarioComent.DesImage;
                    items.photo = usuarioComent.PhotoPerfil;

                }
                if (canlike.Equals(1))
                {
                    item.CanLike = false;
                }
                else
                {
                    item.CanLike = true;
                }
            }
            return View(List);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return RedirectToAction("Index");
        }
    }
}

TelePSocial/Controllers/PubliUsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;
using TelePSocial.Areas.Identity.Data;
using TelePSocial.Data;
using TelePSocial.Entidades;

namespace TelePSocial.Controllers
{
    public class PubliUsersController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly TelePSociaDblContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PubliUsersController(ILogger<HomeController> logger, UserManager<ApplicationUser> userManager, TelePSociaDblContext context)
        {
            _userManager = userManager;
            _context = context;
            _logger = logger;
        }
        public async Task<IActionResult> CreatePubli()
        { 
            var usuario = await _userManager.FindByNameAsync(User.Identity.Name);
            ViewBag.UserName = usuario.Nombre_Usuario;
;
            return PartialView();
        }
        [HttpPost]
        public async Task<IActionResult> CreatePubli(PubliUsers model)
        {
            var usuario = await _userManager.FindByNameAsync(User.Identity.Name);
            model.IdUser = usuario.UserName;
            model.FecPublic = DateTime.Now.Date;
            model.HorPublic = DateTime.Now.TimeOfDay;
            _context.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home" );
        }
        public async Task<IActionResult> LikePubli(int idd)
        {
            var usuario = await _userManager.FindByNameAsync(User.Identity.Name);
            var publi = await _context.PubliUsers.FindAsync(idd);
            var likePubl = new LikesPublics{
                idPubliUsers = idd,
                IdUser = usuario.UserName
            }; 
            _context.Add(likePubl);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Comentar(int idd)
        {
            ViewBag.Id = idd;

            return PartialView();
        }
        [HttpPost]
        public async Task<IActionResult> Comentar(CommentUsers model)
        {
            var usuario = await _userManager.FindByNameAsync(User.Identity.Name);
            model.IdUser = usuario.UserName; 
            model.idPubliUsers = model.idPubliUsers;
            model.FecComment = DateTime.Now.Date;
            model.HorComment = DateTime.Now.TimeOfDay;
            _context.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

    }
}

TelePSocial/Controllers/UserController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;
using TelePSocial.Areas.Identity.Data;
using TelePSocial.Clases;
using TelePSocial.Data;
using TelePSocial.Entidades;

namespace TelePSocial.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly TelePSociaDblContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(ILogger<HomeController> logger, IWebHostEnvironment hostingEnvironment,
            UserManager<ApplicationUser> userManager, TelePSociaDblContext context)
        {
            _userManager = userManager;
            _context = context;
            _logger = logger;
            _hostingEnvironment = hostingEnvironment;

        }
        public async Task<IActionResult> Index()
        {
            var usuario = await _userManager.FindByNameAsync(User.Identity.Name);
            var list = await _context.PubliUsers.Where(z => z.IdUser.Equals(usuario.UserName)).ToListAsync();
            foreach (var item in list)
            {
                item.CantiLikes = await _context.LikesPublics.Where(z => z.idPubliUsers.Equals(item.idPubliUsers)).CountAsync();
                var canlike = await _context.LikesPublics.Where(z => z.idPubliUsers.Equals(item.idPubliUsers) && z.IdUser.Equals(usuario.UserName)).CountAsync();
                item.Comentarios = await _context.CommentUsers.Where(z => z.idPubliUsers.Equals(item.idPubliUsers)).ToListAsync();
                foreach(var items in item.Comentarios)
                {
                    var usuarioComent = await _userManager.FindByNameAsync(items.IdUser);
                    items.username = usuarioComent.UserName;
                    items.usuario = usuarioComent.Nombre_Usuario;
                    items.desPhoto = usuarioComent.DesImage;
                    items.photo = usuarioComent.PhotoPerfil;

                }
                if (canlike.Equals(1))
                {
                    item.CanLike = false;
                }
                else
                {
                    item.CanLike = true;
                }
            }
            ViewBag.ListPub = list;
            return View(usuario);
        }

        public async Task<IActionResult> EditUser()
        {
            var usuario = await _userManager.FindByNameAsync(User.Identity.Name);
            //NOM_ARCHI = await Util.UploadDocument(_hostingEnvironment, item, "Cotizaciones/"),
            return PartialView(usuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(ApplicationUser Model)
        {
            var usuario = await _userManager.FindByNameAsync(User.Identity.Name);


            if (Model.DOC_DOCUM != null)
                {
                    usuario.PhotoPerfil = await Util.UploadImg(_hostingEnvironment, Model.DOC_DOCUM, "Photos/");
                } 
            usuario.FirstName = Model.FirstName;
            usuario.LastName = Model.LastName;
            usuario.Gender = Model.Gender;
            usuario.PhoneNumber = Model.PhoneNumber;
            usuario.FirstName = Model.FirstName; 
            _context.Update(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));  
        }
        public async Task<IActionResult> deletePublic(int idd)
        {
            var publicacion = await _context.PubliUsers.FindAsync(idd);
            _context.Remove(publicacion);
            await _context.SaveChangesAsync();
            //NOM_ARCHI = await Util.UploadDocument(_hostingEnvironment, item, "Cotizaciones/"),
            return RedirectToAction(nameof(EditUser));
        }
        public async Task<IActionResult> verPerfil(string idd)
        {
            var usuario = await _userManager.FindByNameAsync(idd);
            var usuarioLog = await _userManager.FindByNameAsync(User.Identity.Name);
            var list = await _context.PubliUsers.Where(z => z.IdUser.Equals(usuario.UserName)).ToListAsync();
            foreach (var item in list)
            {
                item.CantiLikes = await _context.LikesPublics.Where(z => z.idPubliUsers.Equals(item.idPubliUsers)).CountAsync();
                var canlike = await _context.LikesPublics.Where(z => z.idPubliUsers.Equals(item.idPubliUsers) && z.IdUser.Equals(usuarioLog.UserName)).CountAsync();
                item.Comentarios = await _context.CommentUsers.Where(z => z.idPubliUsers.Equals(item.idPubliUsers)).ToListAsync();
                item.userpubli = await _userManager.FindByNameAsync(item.IdUser);

                foreach (var items in item.Comentarios)
                {
                    var usuarioComent = await _userManager.FindByNameAsync(items.IdUser);
                    items.username = usuarioComent.UserName;
                    items.usuario = usuarioComent.Nombre_Usuario;
                    items.desPhoto = usuarioComent.DesImage;
                    items.photo = usuarioComent.PhotoPerfil;

                }
                if (canlike.Equals(1))
                {
                    item.CanLike = false;
                }
                else
                {
                    item.CanLike = true;
                }
            }
            ViewBag.ListPub = list;
            return View(usuario);
        }

        
        public async Task<IActionResult> BuscarUsuario(string param)
        { 
            var list = await _context.usp_AspNetUsers.FromSqlRaw("usp_AspNetUsers @p0", param).ToListAsync();
            ViewData["Filtro"] = param;
            return View(list);
        }
    }
} 

TelePSocial/Views/Home/Index.cshtml
@model IEnumerable<TelePSocial.Entidades.PubliUsers>

@{
    ViewData["Title"] = "Home Page";
    var user = (string)ViewBag.nombre;
    var photo = (string)ViewBag.photo;
    var DesImage = (string)ViewBag.DesImage;
     
}

<div id="bodysocial">
    <div class="row">
        <div class="col col-md-4"></div>
        <div class="col col-md-4 text-center">
            <br />
            <br />
            <a asp-action="CreatePubli" asp-controller="PubliUsers" class="btn btn-dark add-dialog-window"> Crear publicación </a>
            <br />
            <br /> 
            <div class="container">
                @if(Model.Count() != 0){
                    @foreach(var item in Model)
                    {
                        <br />
                        <br />
                        <div class="card text-left">
                            <div class="card-header headerPubli">
                                @if (!string.IsNullOrEmpty(item.userpubli.PhotoPerfil))
                                {
                                     <a asp-action="verPerfil" asp-controller="User" asp-route-idd="@item.userpubli.UserName" ><img class="mr-3 rounded" src=@Url.Content(item.userpubli.DesImage)  width="45" height="45"  alt="Generic placeholder image"></a>  @item.userpubli.Nombre_Usuario
                
                                }else{
                                     <a asp-action="verPerfil" asp-controller="User" asp-route-idd="@item.userpubli.UserName" ><img class="mr-3 rounded" src="~/images/Feed/usernot.jpg"  width="45" height="45"  alt="Generic placeholder image"></a>  @item.userpubli.Nombre_Usuario
                                } 
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">@item.DesTitle</h5>
                                <p class="card-text">@item.DesPublic .</p>
                            </div>
                            <section>
                                <hr>
                                    <ul class="list-unstyled">
                                      @foreach(var items in item.Comentarios){
                                        <li class="media" style="background: #F5F7FA;">
                                            @if (!string.IsNullOrEmpty(items.photo))
                                            {
                                                <a asp-action="verPerfil" asp-controller="User" asp-route-idd="@items.username" ><img class="mr-3" src=@Url.Content(items.desPhoto)  width="30" height="30"  alt="Generic placeholder image"></a> 
                
                                            }else{
                                                <a asp-action="verPerfil" asp-controller="User" asp-route-idd="@items.username" ><img class="mr-3" src="~/images/Feed/usernot.jpg"  width="30" height="30"  alt="Generic placeholder image"></a> 
                                            } 
                                            <div class="media-body">
                                                <h5 class="mt-0 mb-1">@items.usuario</h5>
                                                @items.DesComment
                                            </div>
                                        </li>   
                                        } 
                                    </ul>
                                </section>
                            <div class="card-footer text-muted">
                                <a class="btn btn-link">@item.CantiLikes me gustas</a>
                                @if (item.CanLike)
                                {
                                    <a asp-action="LikePubli" asp-controller="PubliUsers" asp-route-idd="@item.idPubliUsers" class="btn btn-link ">Like it</a>
                                }
                                @item.FecPublic.ToString().Substring(0,10) @item.HorPublic.ToString().Substring(0,5) 
                                    <a asp-action="Comentar" asp-controller="PubliUsers" asp-route-idd="@item.idPubliUsers" class="btn btn-default addComen-dialog-window ">Añadir Comentario</a>

                            </div>
                        </div>
                        <br />
                        <br />
                    }
                } 
            </div> 
            
        </div>
        <div id="Bodyright" class=" col-md-4 text-right">
            <div  >
            @if (!string.IsNullOrEmpty(photo))
            {
                <p>@user</p><a asp-controller="User" asp-action="Index"><img id="PerfilImage" src=@Url.Content(@DesImage) style="width:100px;max-width: 100%; height: auto;" /></a>
                
            }else{
                <p>@user</p><a asp-controller="User" asp-action="Index"><img id="PerfilImage" src="~/images/Feed/usernot.jpg"/></a>
            }
            </div>
        </div> 
    </div> 
</div>


<div class="modal fade"  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#17a2b8;color:white;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h2 class="modal-title">Agregar Sistema</h2>
            </div>
            <div class="modal-body">
                <div class="teeee">Please wait...</div>
            </div>
        </div>
    </div>
</div>
<div class="modal" id="Add" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Crear publicación</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body"> 
          <div class="teeee"></div>
      </div>
      <div class="modal-footer"> 
      </div>
    </div>
  </div>
</div>
<div class="modal" id="AddComen" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Crear publicación</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body"> 
          <div class="teeeeComen"></div>
      </div>
      <div class="modal-footer"> 
      </div>
    </div>
  </div>
</div>
@section scripts{

<script>
      $("body").on("click", "a.add-dialog-window", null, function (e) {
            e.preventDefault();
            var $link = $(this);
            var url = $(this).attr('href');
            if (url.indexOf('#') == 0) {
                $('#Add').modal('show');
            }
            else {
                $.get(url, function (data) {
                    $('#Add .teeee').html(data);
                    $('#Add').modal();
                }).success(function () { $('input:text:visible:first').focus(); });
            }
        });
        $("body").on("click", "a.addComen-dialog-window", null, function (e) {
            e.preventDefault();
            var $link = $(this);
            var url = $(this).attr('href');
            if (url.indexOf('#') == 0) {
                $('#AddComen').modal('show');
            }
            else {
                $.get(url, function (data) {
                    $('#AddComen .teeeeComen').html(data);
                    $('#AddComen').modal();
                }).success(function () { $('input:text:visible:first').focus(); });
            }
        });
        
</script>
}